### ISSUE TITLE
XDG_DOWNLOAD_DIR

### ISSUE THREAD

**Issue by spirobel** [KnairdA/nixos_home#1]
https://github.com/KnairdA/nixos_home/blob/3dad0c779f22fe2a134c8586460c3e8450fd7036/gui/apps/file.nix#L39
I think the variable is actually called XDG_DOWNLOAD_DIR
source:
https://wiki.archlinux.org/index.php/XDG_user_directories

**Comment by KnairdA** [comment]
Indeed, thank you!
